### PR TITLE
add a through option

### PR DESCRIPTION
**Pull request by jannishuebl**
All work has complete done by @Sanmoo. But since this is also a fix for #23 I want to hint you at his work. For me it works great. 

If you want I can write a test for it.

### CODE REVIEW

**Comment by diogob** [comment]
Nice work, thanks for the PR 👍 
Could you add some test case to cover the new code?

**Comment by jannishuebl** [comment]
I hope the spec are enough. i also can spec the other methods tomorrow.

**Comment by tory** [comment]
@jannishuebl I like it! @diogob can we get this merged in by chance?

**Comment by diogob** [comment]
@jannishuebl thanks again for the PR and sorry for not merging earlier.
@tory I'm merging and releasing a new version.

**Comment by jannishuebl** [comment]
Thank you for merging.

**Pull request merged**
